### ISSUE TITLE
Overpower Rank 1 does not state it "Requires Battle Stance" in the tool tip

### ISSUE THREAD

**Issue by High-Speed-Dirt** [the-hyjal-project/bugtracker#114] opened 2020-12-12 20:57 UTC
**Describe Your Issue**
Overpower Rank 1 does not state it "Requires Battle Stance" in the tool tip

**Steps To Reproduce**
1. Train Overpower rank 1
2. Try to use it in stances other than battle
3. Fail miserably because it requires battle stance

Spell: http://web.archive.org/web/20060621094910/http://www.thottbot.com/?sp=7384
https://classic.wowhead.com/spell=7384/overpower

**Expected Behavior**
Tooltip should show "Requires Battle Stance" in tool tip.

**Comment by Gamemechanicwow** [comment] 2020-12-12 21:00
duplicate of https://github.com/the-hyjal-project/bugtracker/issues/54

Have you tried deleting your cache folder?

**Closed** 2020-12-12 21:09 UTC
