### ISSUE TITLE
GuildRecruitment channel

### ISSUE THREAD

**Issue by alassdaire** [the-hyjal-project/bugtracker#209] opened 2021-01-09 19:36 UTC
Currently when you are in a guild, it is impossible to join the channel "GuildRecruitment".
If you type "/join GuildRecruitment" while in a guild, nothing happens.

Evidence: 
http://wow.gamepedia.com/Patch_1.11.2#User_Interface
"Fixed an issue where the Guild Recruitment channel option could not be enabled."
(Looks like this issue was known on retail too)

http://www.eurogamer.net/articles/news130206blizzardsorry
new guild recruitment channel will be set up, "Providing players with a designated area where they can advertise their guilds in an appropriate fashion".

http://us.battle.net/wow/en/forum/topic/1965571788#2
"in order to join the guild recruitment channel all you have todo it type /join guildrecruitment".

http://www.ehow.com/how_2002110_join-wow-guild.html
"Many guilds advertise for new members on the Guild Recruitment Channel".

Also this channel should be on by default for everyone who is not guilded:
http://wow.gamepedia.com/Patch_1.10.2
"Guild Recruitment channel functionality has been improved to be turned off for players already in guilds, and turned on for players not in guilds by default".

**Comment by Nolin7777** [comment] 2021-01-15 16:27
As one of your research-list says: "Guild Recruitment channel functionality has been improved to be turned off for players already in guilds, and turned on for players not in guilds by default."
Joining and leaving Local-Channels are handled client-side.
As it is not a bug in Vanilla WoW, I will close this ticket.

**Closed by Nolin7777** 2021-01-15 16:27 UTC
Labels: Core related, Player, invalid/wontfix

**Comment by alassdaire** [comment] 2021-01-15 16:41
I don't really understand. At present, people in a guild cannot join the GuildRecruitment channel, and thus its function as a GuildRecruitment channel is negated (how can guildless people be recruited if guilded people can't spam their macros?). What the 'research' says is that someone in a guild should be able to join, but is not in it by default. Presently, they can't join! Furthermore, guildless people should be put in the channel by default.
