### ISSUE TITLE
Miss Danna and children not walking together as a group

### ISSUE THREAD

**Issue by alassdaire** [the-hyjal-project/bugtracker#207] opened 2021-01-09 18:44 UTC
**Describe Your Issue**
Miss Danna and her group of schoolchildren are not presently walking together as a group in Stormwind, as they should do. This is similar to my previous report about Suzanne/Janey/Lisan. 
**Steps To Reproduce**

1. Go to Stormwind.
2. Find Miss Danna and the children listed below.
3. Note that the various schoolchildren are scattered around the city, rather than walking together with Miss Danna.

Miss Danna:
https://classic.wowhead.com/npc=3513/miss-danna
The children:
https://classic.wowhead.com/npc=3505/pat
https://classic.wowhead.com/npc=3512/jimmy
https://classic.wowhead.com/npc=3510/twain
https://classic.wowhead.com/npc=3508/mikey
https://classic.wowhead.com/npc=3507/andi
https://classic.wowhead.com/npc=3511/steven

**Expected Behavior**

Miss Danna and the children listed above should walk together, and have a dialogue.

**Comment by Neto-WoW** [comment] 2021-03-05 01:49
I've followed these around for a while and let them run for about an hour. Although they do get split up slightly, they are always moving together and end up gathering at the front of Stormwind as intended. I'd need to see more video or photographic evidence to catch exactly which point is causing the issue.  Speeds are all the same, wait times are all correct.  One child is meant to lag behind but always catches up.

Please reopen and resubmit if you have more video or picture evidence. Thanks!

**Closed by Neto-WoW** 2021-03-05 01:49 UTC
Labels: Database, Low Priority, NPC
